### PR TITLE
Update Prod container app after image push

### PR DESCRIPTION
**Pull request by Stretch96**
* Once the image is pushed to ECR, this then updates the container app to use the newly built image

### CODE REVIEW

**Comment by chrisdexnimble** [comment]
@Stretch96 
Will the pipeline continually deploy new versions of a release, if for example the release-8 tag is not updated for a while. 
Or will only the first version of a release be the one that is deployed ?

**Comment by Stretch96** [comment]
The release-8 tag, shouldn't be moved, so it will always just deploy that version
When there is a new release, the workflow file can be updated to eg. release-9

**Comment by chrisdexnimble** [comment]
> The release-8 tag, shouldn't be moved, so it will always just deploy that version When there is a new release, the workflow file can be updated to eg. release-9

Thanks.
What I mean is, if we push to the main branch multiple times without updating from release-8. Will that cause multiple releases to be pushed ?

effectively 
release-8 v1
release-8 v2
release-8 v3

or will prod remain fixed at the first release-8 it found (so release 8 v1).

I think you're confirming that only the first release tag will be deployed. In which case I can approve this.
But if not then I will wait until after change freeze is over.

**Comment by Stretch96** [comment]
The workflow will run on a push to main, however, it checks out `release-8` and builds from there

When it pushes the image, there will be no change, so there won't be release-8 v1,v2 etc

It's safe to push to main, without it affecting the Test or Prod environments

**Review by chrisdexnimble — APPROVED** [review]

**Pull request merged**
